language: go

env:
  - GO111MODULE=on

go:
  - 1.11.x

install:
  true

notifications:
  email: true

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run
